const starsData = [
    {
        id: 1,
        title: "Sessizce Güzelleşen",
        task: "click",
        image: "assets/images/star-01.jpg",
        position: { top: '15%', left: '50%' },
        message: `Yağmur…
bu fotoğrafa baktığımda ilk fark ettiğim şey güzelliğin olmuyor…
garip ama önce bıraktığın his geliyor… 🤍
Sanki insan bir anlığına duruyor…
etraftaki her şey biraz uzaklaşıyor…
ve gözler sadece sana takılıp kalıyor…
Sende öyle bir şey var ki…
bağırarak dikkat çekmiyor…
tam tersine…
sessizce kendini fark ettiriyor…
Ben bazen düşünüyorum…
insan neden bazı yüzleri görünce normal devam edemiyor diye…
sonra cevabını sende buluyorum…
Çünkü sen sadece güzel görünmüyorsun Yağmur…
sen güzel bir his bırakıyorsun…
Ve bence…
asıl unutulmayan şey de tam olarak bu… 🤍`
    },

    {
        id: 2,
        title: "Gülüşünün Bıraktığı Şey",
        task: "input",
        question: "Benim için kim olduğunu söyle…",
        answer: "yağmur",
        hint: "Güzel adın...",
        image: "assets/images/star-02.jpg",
        position: { top: '15%', left: '20%' },
        message: `Yağmur…
sen gülünce çok garip bir şey oluyor… 🤍
Sanki o anın içinde ne varsa…
bir anda daha güzel görünmeye başlıyor…
Bunu nasıl yaptığını gerçekten bilmiyorum…
ama gülüşünün sadece yüzünde kalmadığını hissediyorum…
karşısındaki insana da geçiyor…
Bazı insanlar güler…
sonra o an biter…
ama senin gülüşün insanın aklında biraz daha kalıyor…
Belki de bu yüzden…
seni düşündüğümde aklıma sadece yüzün gelmiyor…
o gülüşün bıraktığı sıcaklık geliyor…
Ve itiraf edeyim…
bazı günler bir insanın gülümsemesini düşünmek bile
günün geri kalanını güzelleştirmeye yetiyor… 🤍`
    },

    {
        id: 3,
        title: "Bakışlarının İçinde",
        task: "password",
        password: "yağmur",
        hint: "Adının kendisi…",
        image: "assets/images/star-03.jpg",
        position: { top: '30%', left: '75%' },
        message: `Bazen gözlerine bakınca…
bir şey anlatıyormuşsun gibi geliyor bana… 🤍
Ama ne anlattığını tam olarak çözemiyorum…
Belki sakinliği…
belki masumluğu…
belki de sadece sende olan o tarif edemediğim şey…
Çünkü bazı bakışlar vardır…
insan görür ve geçer…
Bazılarıysa insanın aklında kalır…
seninki biraz öyle…
Uzun uzun düşününce bile
tek bir kelime bulamıyorum…
Sadece şunu söyleyebiliyorum:
bakışlarında insanın tekrar bakmak istemesine neden olan
bir dünya var…
Ve ben galiba…
o dünyanın yolunu bulmayı seviyorum… 🤍`
    },

    {
        id: 4,
        title: "Bir Çiçekten Fazlası",
        task: "click",
        image: "assets/images/star-04.jpg",
        position: { top: '45%', left: '15%' },
        message: `Şu fotoğrafa bakarken…
ilk başta gözüme çarpan şey çiçek oldu… 🤍
Sonra sana baktım…
Ve çiçek bir anda arka planda kaldı…
Çünkü bazı şeyler güzel oldukları için dikkat çeker…
bazılarıysa güzelliği bile kendi yanında küçük gösterir…
Senin yanında olan herhangi bir şeyin
bir anda ikinci planda kalabilmesi
biraz haksızlık gibi geliyor bana… 😅
Ama asıl sevdiğim şey…
bunu farkında olmadan yapman…
Hiç uğraşmadan…
hiç zorlamadan…
sadece olduğun gibi durarak…
Ve galiba gerçek zarafet de tam olarak bu…
kendini göstermeye çalışmadan
kendini belli etmek… 🤍`
    },

    {
        id: 5,
        title: "Huzurun Olduğu Yer",
        task: "date",
        targetDate: "2012-07-13",
        hint: "Özel olan tarih...",
        image: "assets/images/star-05.jpg",
        position: { top: '60%', left: '50%' },
        message: `Bazı fotoğraflar insana heyecan verir…
bazıları huzur…
Bu bana direkt seni düşündürenlerden… 🤍
Çünkü sende çok sevdiğim bir şey var:
insanı yormayan bir güzellik…
Sana bakınca insanın içi karışmıyor…
tam tersine biraz sakinleşiyor…
Sanki bütün gün ne kadar yorulmuş olursam olayım
bir anlığına her şeyi bırakıp
sadece o ana bakabiliyorum…
Ve sonra fark ediyorum…
huzur dediğimiz şey bazen bir yer değilmiş…
Bazen bir insanmış…
Bazen sadece adını görünce bile
içinde küçük bir rahatlama olan biriymiş…
Ve benim için o his…
seninle fazlasıyla aynı yerde duruyor… 🤍`
    },

    {
        id: 6,
        title: "Sana Yakışan Dünya",
        task: "hold",
        duration: 3000,
        isSpecial: true,
        image: "assets/images/star-06.jpg",
        position: { top: '40%', left: '50%' },
        message: `Bu fotoğrafa bakınca…
nedense gülümsedim… 🤍
Ama fotoğraftaki şey yüzünden değil…
Senin o anın içinde oluşun yüzünden…
Çünkü bazı insanlar bir ortama dahil olur…
bazı insanlarsa bulunduğu ortamın havasını değiştirir…
Sanki senin olduğun yerde
her şey biraz daha anlamlı oluyor…
Ve en güzel kısmı şu:
bunu yapmak için hiçbir şey yapmıyorsun…
Sadece varsın…
Belki kulağa fazla basit geliyor ama
bazen bir insanın en güçlü özelliği
tam olarak kendi haliyle güzel olabilmesi…
Ve Yağmur…
senin olduğun bazı anlar
izlenmiyor…
hissediliyor… 🤍`
    },

    {
        id: 7,
        title: "Gözümün Sana Gitmesi",
        task: "click",
        image: "assets/images/star-07.jpg",
        position: { top: '75%', left: '25%' },
        message: `Biliyor musun…
bazen bir fotoğrafa bakarken
gözüm neden özellikle sana gidiyor diye düşünüyorum… 🤍
Sonra cevabın çok basit olduğunu fark ediyorum…
Çünkü sende dikkat çeken bir şey var…
Ama bu öyle herkesin yaptığı gibi
“beni fark edin” diye bağıran bir şey değil…
Tam tersine…
sen hiçbir şey yapmadan fark ediliyorsun…
Ve bu daha etkileyici…
İnsan önce bir kez bakıyor…
sonra bir kez daha…
Sonra fark ediyor ki
aslında fotoğrafı incelemiyor…
seni izliyor…
Benim başıma gelen de tam olarak bu… 🤍`
    },

    {
        id: 8,
        title: "Biraz Daha Yakından",
        task: "memory",
        pairs: 4,
        image: "assets/images/star-08.jpg",
        position: { top: '30%', left: '85%' },
        message: `Sende çözmek istediğim bir şey var Yağmur… 🤍
Neden her baktığımda
seni ilk baktığımdan biraz daha farklı görüyorum?
Bir gün gözlerin dikkatimi çekiyor…
bir gün gülüşün…
başka bir gün sadece yüzündeki ifade…
Sonra anlıyorum ki
mesele tek bir detay değil…
Sen bütünüyle merak uyandırıyorsun…
Ve bu çok güzel bir şey…
Çünkü bazı insanlar ilk bakışta her şeyini gösteriyor…
sende ise her bakışta başka bir küçük ayrıntı kalıyor…
Belki de bu yüzden
sana bakmak hiç gerçekten “bakıp geçmek” olmadı…
Her seferinde biraz daha kalmak gibi… 🤍`
    },

    {
        id: 9,
        title: "Eksik Parça",
        task: "dragdrop",
        letters: ['Y', 'A', 'Ğ', 'M', 'U', 'R'],
        image: "assets/images/star-09.jpg",
        position: { top: '75%', left: '65%' },
        message: `Bu fotoğrafta her şey tamam gibi görünüyor… 🤍
Ama yine de insanın gözü
bir şey arıyor…
Sonra fark ediyorum:
o şey sensin…
Çünkü bazı görüntüler güzel olabilir…
ama onları özel yapan şey
içlerinde sakladıkları anlamdır…
Sen de benim için biraz öylesin…
Bir yere, bir ana, bir güne
sen dahil olduğunda
aynı şey artık aynı şey gibi gelmiyor…
Sanki küçük bir detay gelip
bütün resmi değiştiriyor…
Ve bazen…
hayatın güzel olması için
çok büyük şeylere gerek olmadığını düşünüyorum…
Bazen sadece doğru insanın
doğru anda hayatında olması yetiyor… 🤍`
    },

    {
        id: 10,
        title: "İlk Bakışta Kalmayan",
        task: "click",
        image: "assets/images/star-10.jpg",
        position: { top: '45%', left: '25%' },
        message: `Seni ilk gördüğüm anda
güzel olduğunu düşünmek kolaydı… 🤍
Ama zaman geçtikçe
fark ettiğim şey güzelliğinden daha başka oldu…
Çünkü ilk bakış bir insanın yüzünü gösterir…
zaman ise onda ne bulduğunu…
Ve sende sadece güzellik bulmadım…
Merak buldum…
sıcaklık buldum…
huzur buldum…
Belki de bu yüzden
seni ilk gördüğüm anla
seni şimdi düşündüğüm an aynı değil…
Çünkü bazı insanlar
ilk bakışta etkiler…
bazılarıysa zaman geçtikçe
insanın içine daha da yerleşir…
Sen ikinci türdensin… 🤍`
    },

    {
        id: 11,
        title: "Adını Söyleyince",
        task: "password",
        password: "yağmur",
        hint: "Sadece adını yaz...",
        isGolden: true,
        flashEffect: true,
        image: "assets/images/star-11.jpg",
        position: { top: '60%', left: '80%' },
        message: `Yağmur…
adını söylemek bile bazen garip bir şekilde
içimi yumuşatıyor… 🤍
Belki sadece dört harf…
ama bende bıraktığı şey
dört harften çok daha büyük…
Bir insanın adını duyunca
neden yüzünde istemsiz bir gülümseme oluşur ki?
İşte sen bunu yaptın…
Bazen hiçbir şey olmuyor…
normal bir gün geçiyor…
sonra aklıma bir anda sen geliyorsun…
Ve o küçücük an
günün geri kalanından ayrılıyor…
Çünkü senin adın benim için
sadece bir isim değil artık…
Bir yüz…
bir gülüş…
bir bakış…
bir sürü küçük an…
Ve bütün bunların ortasında
tek bir isim kalıyor:
Yağmur… 🤍`
    },

    {
        id: 12,
        title: "Benim İçin Sen",
        task: "final",
        isFinal: true,
        image: "assets/images/star-12.jpg",
        position: { top: '85%', left: '75%' }
    }
];

const finalMessage = `İşte…
son yıldıza da geldik Yağmur… 🤍
Ve garip olan şu…
buraya kadar gelirken aslında
12 fotoğrafa bakmadım ben…
12 farklı anda seni gördüm…
Bazen güzelliğini…
bazen gülüşünü…
bazen bakışını…
bazen de sadece sende bıraktığın o hissi…
Her yıldızda farklı bir şey anlatmaya çalıştım…
ama hepsinin altında
aynı gerçek vardı…
Sen benim için sıradan bir insan olmadın…
Öyle sessizce…
fark ettirmeden…
bir şeyleri değiştirdin…
Bazen sadece adını düşünmek bile yetti…
bazen bir fotoğrafın…
bazen küçücük bir anın…
Ve insanın en sevdiği şeylerin
illa büyük olması gerekmiyor…
Bazen bir gülüş oluyor…
bazen bir mesaj…
bazen bir bakış…
Ama hepsi aynı kişiye ait olduğunda
anlamı değişiyor…
Benim için sen biraz da busun…
Küçük şeyleri büyüten biri…
Sıradan bir günü hatırlanacak hale getiren…
basit bir anı özel yapan…
ve bazen hiçbir şey yapmadan
insanın yüzünde bir gülümseme bırakan biri…
Belki bunu kelimelerle tamamen anlatamam…
Hatta bazen anlatmaya çalışırken
aynı cümleleri tekrar tekrar kurarım…
Ama nedeni çok basit:
Çünkü bazı hisler
birkaç güzel cümleye sığmıyor…
Sen de benim için
öyle birkaç kelimeyle anlatılacak biri değilsin…
Ve belki bütün bu sitenin sonunda
sana söylemek istediğim en basit şey şu:
İyi ki varsın Yağmur…
Çünkü bazı insanlar hayatımıza girer…
bazılarıysa hayatımızın bir parçası olur…
Sen…
bende güzel bir iz bırakanlardan oldun… 🤍
Ve ne kadar zaman geçerse geçsin…
Seni düşündüğümde içimde
aynı sıcaklığın kalmasını seviyorum…
✨
Sen…
bu küçük galaksinin
en sevdiğim yıldızısın… 🤍`;